# syntax=docker/dockerfile:1
FROM mambaorg/micromamba:focal

USER root
RUN apt-get update && \
  apt-get install -yq tzdata && \
  ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata
USER $MAMBA_USER

RUN <<EOF cat > long_read.yml
name: long_read
channels:
  - conda-forge
  - bioconda
dependencies:
  - nanoplot=1.41.6
  - minimap2=2.26
  - samtools=1.16.1
  - flye=2.9.2
EOF

RUN micromamba install -y -n base -f long_read.yml && \
  micromamba clean --all --yes

ENV PATH "/opt/conda/bin:$PATH"