# syntax=docker/dockerfile:1
FROM mambaorg/micromamba:focal

USER root
RUN apt-get update && \
  apt-get install -yq tzdata && \
  ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata
USER $MAMBA_USER

RUN <<EOF cat > prodigal.yml
name: prodigal
channels:
  - bioconda
  - conda-forge
dependencies:
  - prodigal=2.6.3
  - pplacer=1.1.alpha19
  - hmmer=3.3.2
  - numpy=1.24.2
  - matplotlib-base=3.7.0
  - pysam=0.20.0
  - python=3.10.8
EOF

RUN micromamba install -y -n base -f prodigal.yml && \
  micromamba clean --all --yes

ENV PATH "/opt/conda/bin:$PATH"

RUN pip3 install checkm-genome